# Generated by Django 4.2.3 on 2023-07-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_csvdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
