# Generated by Django 4.2.3 on 2023-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
